---
title: "Ch. 3: Estimation: How Large Is the Effect?"
author: ""
output:
  xaringan::moon_reader:
    css: ["css/default.css", "css/default-fonts.css"]
    mathjax: "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_HTMLorMML"
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({ TeX: { extensions: ["color.js"] }});
</script>

```{r setup, include = F}

library(ggplot2)
library(tidyverse)
knitr::opts_chunk$set(dpi=300, message = F, warning = F, echo = F, fig.width = 8, fig.height = 4, out.width = "80%", fig.align = "center", cache = T)
theme_set(theme_bw())
```

# Navigation

.pull-left[
.large[By Date]

- February 18: [start](#3) - [end](#10)

]
.pull-right[
.large[By Section]

]

---
class:inverse,middle,center
# 3.1: Statistical Inference: Confidence Intervals

---
## Exploration 3.1

Most people are right-dominant. In a study reported in Nature (2003), researchers showed that couples tend to lean their heads to the right while kissing. The researchers observed kissing couples in various public places and recorded which direction their heads tilted, excluding any couples who were holding objects that might affect the direction they turned. They observed that 80 of 124 couples leaned their heads to the right.

In groups, identify the observational units, variable of interest, and whether the variable is categorical or quantitative. 

---
## Exploration 3.1

The researchers observed that 80/124 couples leaned right.

Let $\pi$ denote the proportion of all kissing couples that turn their heads to the right.

- Is $\pi$ a parameter or a statistic?

- Do we know the value of $\pi$?

- Calculate $\hat p$

- State the hypotheses:


---
## Exploration 3.1

Conduct a simulation for the previously stated hypotheses. Report the p-value and state your conclusion.


---
## Exploration 3.1

We have evidence that the true proportion of couples who lean right is not 0.5. Maybe it's 0.6?

Test $H_0: \pi=0.6$


---
## Exploration 3.1

Suppose we want to estimate the long-run proportion of couples who lean their head to the right while kissing. 

- Would 0.5 be in your 95% confidence interval? Why or why not?

- Would 0.6 be in your 95% confidence interval? Why or why not?

- Use the applet to try different values and determine where the lower and upper cutoffs are for your confidence interval.


---
## Exploration 3.1

.pull-left[
Lower Bound: 

P under $H_0$ | 2-sided p-value | Conclusion
------------- | --------------- | ----------
0.54 | | 
0.55 | | 
0.56 | | 
0.57 | | 
0.58 | | 
0.59 | | 
]

.pull-right[
Upper Bound: 

P under $H_0$ | 2-sided p-value | Conclusion
------------- | --------------- | ----------
0.71 | |
0.72 | |
0.73 | |
0.74 | |
0.75 | |
0.76 | |
]

---
## Exploration 3.1

Interpret your confidence interval in the context of the scenario:


---
## Section 3.1 Summary

- "Simulating" confidence intervals
  - Trying many different parameter values
  - Testing: which ones do we reject (not plausible), and which ones do we fail to reject? (plausible value)

- What level we reject at dictates our "Confidence Level"
  - Significance level + Confidence level = 1
  - Reject less than 0.05, 95% Confidence level
  - Reject less than 0.10, 90% Confidence level
  - Which one is wider?
  
- Connection between p-value and confidence interval
  - Significance level + Confidence level = 100%

---
class:center,middle,inverse
# 3.2: 2SD and Theory-Based Confidence Intervals For a Single Proportion


---
## Theory Based Method

- We do not want to plug in those parameter values every time we want an interval

- Method boils down to one idea:     
We're finding a set of plausible values for the parameter centered around the .underline[.hidden[sample mean]] and adding some wiggle room around it.

- The wiggle room is known as the .underline[.hidden[margin of error]]

---
## Confidence Interval

So the basic set up for our confidence interval is:
$$\text{Sample statistic}\pm \text{margin of error}$$

Margin of error is based on two values:
1. The .underline[.hidden[standard deviation]] of the sample statistic
2. A .underline[.hidden[multiplier]] reflecting the confidence level we want

Thus the margin of error is...


---
## Multiplier

- The multiplier is based on the confidence level (Sec 3.1)

- For a .underline[.hidden[higher]] confidence level, the multiplier must get bigger
  - Want a .underline[.hidden[wider]] interval to cover more plausible values

  
- For a .underline[.hidden[lower]] confidence level, the multiplier will be smaller
  - Leads to a .underline[.hidden[narrower]] interval
  - But we don't have as much confidence

---
## Multiplier
- We will use a multiplier of $\pm 2$ in this class

- Why?
  - Bell shaped distribution
  - 95% of the distribution captured within 2 standard deviations of the center of the null distribution
  - True parameter will be within two standard deviations of the observed sample statistic in about 95% of samples
  - Where else do we use $\pm 2$ in this class?

- Other confidence levels lead to different multipliers
  - We will always use 95% in this class
  
